Feature/state-options
BloomTech-Labs/underdog-devs-fe-a pull request #102
Opened 2022-02-22 20:53 UTC by Fvaldenegro95

## Description

Cleaned up a large chunk of repeated code under the dropdown for state selection on the Mentee application; created the array of states over to a constant folder that can be used in any other part of the application.

##File Changed

src/components/pages/RoleSignup/Applications/Mentee.js

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-02-22 21:00 UTC, MrJacobSullivan approved these changes

2022-02-22 21:00 UTC, MrJacobSullivan commented on src/components/pages/Profile/EditProfile.js
> +export default connect(mapStateToProps)(EditProfile);
I believe this is part of another PR you are working on. I'm not sure how to remove it from this PR.

2022-02-22 21:18 UTC, ryansnorek requested changes
Code looks good. Now all we need is to do the same thing in the Mentor component. I see one edit otherwise in `/constants/index` the line `export default states` that could come up later

What if we need to add more exports in `constants` later on?  It would still work with default but might be better off doing a regular `export states` in the index.js, and then in Mentee.js it would be `import { states } ...`

2022-02-22 23:31 UTC, EnasELM approved these changes

2022-02-23 16:55 UTC, ryansnorek approved these changes

2022-02-24 19:53 UTC, paulstgermain requested changes
This PR needs a Loom walkthrough video! 😱 

Please add one as soon as you can, so I can come back and review and merge up your work!

2022-02-28 05:56 UTC, paulstgermain approved these changes

2022-02-28 05:57 UTC, merged