Feature/application modal
BloomTech-Labs/underdog-devs-fe-a pull request #103
Opened 2022-02-23 01:23 UTC by LmCastelli

## Description

This PR adds a fully styled modal to the Pending Application component that shows all information for the applicant selected. Additionally, in the table, the date column has been sliced to remove the unnecessary info (exact hour, minute, second, etc. of time) and only has the day, month, and year. The dropdown has also been removed as it has been deemed unnecessary.

https://www.loom.com/share/aa3fb8e037b74799b61663e04db6d300

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

## Contributors: 
@rdperry031 
@cainpalmer 
@LmCastelli

2022-02-23 15:55 UTC, MrJacobSullivan requested changes

2022-02-23 16:16 UTC, EnasELM approved these changes

2022-02-23 23:36 UTC, MrJacobSullivan approved these changes
Thank you for making those changes. This is a crucial component for getting users registered with Okta. Nice work!

2022-02-28 06:07 UTC, paulstgermain commented on src/components/pages/PendingApplications/ApplicationModal.js
> +                  <li>Job Help</li>
What do we think about changing this to 'Job Search Help' or 'Career Readiness Help' or something similar? 'Job Help' could either mean help with your current job OR help getting hired, and clarity is always a good thing. Just a suggestion, not a change we need to make straightaway.

2022-02-28 06:09 UTC, merged