added styling for notes buttons
BloomTech-Labs/underdog-devs-fe-a pull request #110
Opened 2022-02-25 22:36 UTC by cainpalmer

## Description

This PR adds extra styling for the notes buttons that will appear in the pending applications modal to add functionality to the notes text box. We included the proper colors to keep the site color palette consistent, removed generic button borders, and added some padding to create fancy styling for the user to experience when updating an applicants notes.

Loom: https://www.loom.com/share/dc2750e3f56f4811a6d28df5e888c3cf

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

## Contributors:
@rdperry031 
@LmCastelli 

## Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have removed unnecessary comments/console logs from my code
- [ x] I have made corresponding changes to the documentation if necessary (optional)
- [ x] My changes generate no new warnings
- [ x] I have checked my code and corrected any misspellings
- [ x] No duplicate code left within changed files
- [ x] Size of pull request kept to a minimum
- [ x] Pull request description clearly describes changes made & motivations for said changes

2022-02-25 22:57 UTC, Jaredhall18 requested changes
This looks so good! I noticed the button to save notes has the text written as follows "Save notes" This looks odd. Could you change this to "Save Notes"?

--NOTE-- This is getting covered in a different PR!

2022-02-25 23:03 UTC, Jaredhall18 approved these changes

2022-02-26 01:11 UTC, EnasELM approved these changes
This style looks so good. nice work!

2022-02-28 06:49 UTC, merged

2022-02-28 16:31 UTC, tarasshulhan reviewed
Looks good!