reformatted application forms
BloomTech-Labs/underdog-devs-fe-a pull request #134
Opened 2022-03-08 18:14 UTC by BryceSlade

[Loom Video](https://www.loom.com/share/cead7e3de9444b9aba202886057828f5)

## Description

This branch involved small changes to the application forms for the mentor and mentee. Now, all required fields share the same styling and all have the required star next to the label. Additionally, I cleaned up some of the styling to line up the form items and make it look more cohesive. This makes for a much cleaner application page. 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

2022-03-08 18:35 UTC, BryceSlade commented
May need the UX team to go over these changes and determine what they are looking for. The wireframes show another style and it could have gone one of two ways. Keep the red required star on all forms, changing the style of the whole page, or keeping the text star in the heading tags (form validation will still work).

2022-03-08 20:44 UTC, tarasshulhan approved these changes

2022-03-09 16:44 UTC, morgankj approved these changes

2022-03-09 16:46 UTC, fletchulence commented on src/components/pages/RoleSignup/Applications/Mentor.js
> +                {/* <Col span={24}>
get rid of the comment

2022-03-09 16:48 UTC, fletchulence requested changes
change the small things for formatting

2022-03-09 16:58 UTC, BryceSlade commented on src/components/pages/RoleSignup/Applications/Mentee.js
> +                      that apply)"
This has been fixed. Thank you for catching that!

2022-03-09 17:01 UTC, BryceSlade commented on src/components/pages/RoleSignup/Applications/Mentor.js
> +                {/* <Col span={24}>
Comments removed!

2022-03-09 18:47 UTC, BryceSlade commented
> 

Yes, these are from other components from different teams

2022-03-10 07:46 UTC, paulstgermain commented on src/components/pages/RoleSignup/Applications/Mentee.js
> +import React from 'react';
Good eye for cleaning up potential Linter warnings here.

2022-03-10 07:50 UTC, paulstgermain approved these changes
Thorough, consistent use of Ant Design components for our forms throughout - even introducing them in areas that weren't using them before - plus some clearly well-thought-out styling changes (Incremental progress, maybe, but vital to the flow of these forms!) and both a solid description and Loom walkthrough equals an easy pass from me.

Great work!

2022-03-10 07:50 UTC, merged