Adding the my notes component
BloomTech-Labs/underdog-devs-fe-a pull request #169
Opened 2022-04-04 16:15 UTC by areccus

## Description

___Add your PR description here, deleting this example___

#### Video Link

https://www.loom.com/share/7ed04b4e9f9741498131e510547e5757

#### Contributors
Anthony "@acoman-cloud" Coman

## Type of change

___Please delete options that are not relevant.___

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

2022-04-04 16:33 UTC, acoman-cloud approved these changes
Great work! Nice to see some clean up and functionality being added.

2022-04-04 18:48 UTC, morgankj approved these changes
Touched quite a few files here, which always makes me nervous XD But it looks like your changes were clean and dry! Good work following best practices too; you did a good job of removing unused imports and blocks

2022-04-04 18:48 UTC, morgankj commented on src/components/common/NotesTable/NoteUtils.js
> -// Flag Styling
I like this change of adding the styling into its own doc - much cleaner and easier to follow in my opinion

2022-04-04 18:48 UTC, morgankj commented on src/components/common/NotesTable/NoteUtils.js
> +// Flag Icons
Good comments here to clue in other devs

2022-04-04 20:27 UTC, maidiance requested changes
Overall looks great. Please be sure to clean up excess console logs though!

2022-04-04 20:27 UTC, maidiance commented on src/components/common/NotesTable/index.js
> +  console.log(userProfile);
This console log should be removed.

2022-04-04 20:27 UTC, maidiance commented on src/components/common/NotesTable/index.js
> +  console.log(location.pathname);
Do not leave console logs in your code.

2022-04-04 23:11 UTC, phillipgalbraith reviewed
This pull request is description is effective in referencing specific reasons for changing or adding code and the methods used.  Consider moving the Notes.js inline styles to Notes.css with classes.

2022-04-05 15:56 UTC, arsalan2243 approved these changes
this looks clean and adding better functionality. if you remove the console logs it would be good to go.

2022-04-06 00:50 UTC, beefybroccoli approved these changes
Thes scope is sufficiently small. The new functionality is needed.

2022-04-06 23:33 UTC, merged