Changed update button
BloomTech-Labs/underdog-devs-fe-a pull request #187
Opened 2022-04-08 11:32 UTC by arsalan2243

## Description

change of update button color to have a better contrast in relation to cancel button.

#### Video Link

https://www.loom.com/share/2ba9c5330efd4385a2f6cf46f47af322

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-08 13:36 UTC, maidiance requested changes
This does not look like it's following the style guidelines of the project. Please speak to Swapnali and make sure these changes are approved.

2022-04-08 16:25 UTC, fletchulence commented
> 

Feels like this could be a quick fix, did you check with Swapnali about the styleguide?

2022-04-08 16:28 UTC, fletchulence requested changes
Black/white are usually not a style preferred by UX. A bit too hard on the eyes from what i understand. Talk to Swapnali and ask her opinion about it - im sure she will be happy to help!

2022-04-12 14:30 UTC, ChristianSmith2394 requested changes
As the others have said, not a huge fan of the black and white buttons. They're hard on the eyes. I like the transition into the blue, but think the buttons would just be better off being blue from the start to match the rest of the UI

2022-04-19 14:31 UTC, xokeixo commented on src/components/pages/PendingApplications/PendingApplication.js
> +                    color: '#FFFFFF',
Black button on a blue gradient background? I feel as though that'll be super hard to read for anyone. Maybe something a little better on the eye?

2022-05-04 04:50 UTC, closed without merging