Nav bar UI fix
BloomTech-Labs/underdog-devs-fe-a pull request #193
Opened 2022-04-15 19:00 UTC by JCSime

## Description

- Removes ‘Account’ from sidebar
- Adds an alt and aria-label to the far right of nav bar that says ‘Account settings’ for accessibility readers
- Adds icons to ‘Account settings’ nav bar dropdown menu
- Removes unnecessary ‘Memo’ dropdown menu from nav bar
- Changes the color of the nav ‘Memo’ button to white for accessibility reasons

#### Video Link

[Loom Video] https://www.loom.com/share/6fc8faefec264f638286b636d94bfacd

#### Trello Link

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uUKuzW1H&#x2F;311-as-a-user-the-ui-features-on-the-sidebar-and-nav-bar-are-attractive-and-easy-to-find">As a user the UI features on the sidebar and nav bar are attractive and easy to find</a></blockquote><script src="https://p.trellocdn.com/embed.min.js"></script>

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-15 19:21 UTC, aaronamendez commented
Looks good guys, great job as a coding pair!

2022-04-18 14:23 UTC, Jmz0127 reviewed
Love the addition of screen readers to the menu bar to boost accessibility. way to go!

2022-04-18 15:46 UTC, Collyngodlewski commented
Nice!! The dropdown looks a lot cleaner there and nice you added the screen reader aspect. Wonderful job guys

2022-04-18 18:17 UTC, kimnivore commented on src/components/pages/Navbar/Navbar.js
> +                        alt="Account settings"
I like how you added the alt tags for screen readers. Thanks for demonstrating this in the video. It was really helpful seeing it in action.

2022-04-18 18:24 UTC, kimnivore approved these changes
Your code was easy to understand. I like the addition of the alt tags for screen readers. Great job!

2022-04-18 18:38 UTC, BrittanyPete requested changes
It looks like there are a few things that are defined but never used. Could you help clear some of that up? Examples: Link, Modal, UserOutlined, LogoutOutlined, modal, openModal, cancelOpen, handleLogout, axiosWithAuth, useForms. Other than that, I really like how you guys incorporated the alt tags for screen readers!

2022-04-19 14:27 UTC, xokeixo reviewed
Everything looks great! Very readable and accessible.

2022-04-19 16:50 UTC, JCSime commented
> It looks like there are a few things that are defined but never used. Could you help clear some of that up? Examples: Link, Modal, UserOutlined, LogoutOutlined, modal, openModal, cancelOpen, handleLogout, axiosWithAuth, useForms. Other than that, I really like how you guys incorporated the alt tags for screen readers!

Just pushed those changes, thanks for giving me the heads up about those! Forgot to clean that up after Ryan mentioned it in the meeting.

2022-04-19 21:46 UTC, merged