got images to be the same size and have a clean look in uniformity
BloomTech-Labs/underdog-devs-fe-a pull request #197
Opened 2022-04-20 18:04 UTC by ChristianSmith2394

## Description

There was an issue with UI/UX causing images and text to be out of uniform upon applying. Created uniformity to allow for a clean user experience.

#### Video Link

[Loom Video](https://www.loom.com/share/83b5d47986004519ac6447096f8b7160)

#### Trello Link

https://trello.com/c/rEbB5Yw6/332-misalignment-issues-with-mentee-and-mentor-elements

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-04-20 18:12 UTC, mikayla-kosmala commented
I love it, but are we able to change the button to go underneath the text? The button its self looks scrunched as well.

2022-04-20 18:17 UTC, BrittanyPete requested changes
It is looking so much better! As has been mentioned though, I'm wondering if we can work on the button a little bit too. It looks small and is a little difficult to read. Not sure if it would be better under the text, or maybe the text column could be a little bit smaller, and the column with the button could be a little wider.

2022-04-20 19:32 UTC, mikayla-kosmala approved these changes

2022-04-20 19:35 UTC, BrittanyPete approved these changes

2022-04-22 01:47 UTC, Collyngodlewski approved these changes
After spending about an hour in discord together, I'm glad you got it figured out. Looks a lot better than it did before!

2022-04-22 14:08 UTC, malloryshea commented
Nice job resizing and getting everything in order. As mentioned in previous comments the button is the only thing I'm having a hard time reading, maybe enlarge the button as well as the text size?

2022-04-22 14:09 UTC, malloryshea approved these changes

2022-04-22 15:18 UTC, yuririnnnu approved these changes

2022-04-23 00:32 UTC, paulstgermain commented on src/components/pages/RoleSignup/Signup.js
> +                // style={{ height: '100%' }}
We may want to remove these commented-out pieces of code down the line!

2022-04-23 00:33 UTC, paulstgermain commented on src/components/pages/RoleSignup/Signup.js
> +                // style={{ height: 100 }}
Another exampled of commented-out code to remove later!

2022-04-23 00:35 UTC, merged