added "how did you hear about underdog devs" question to mentee form
BloomTech-Labs/underdog-devs-fe-a pull request #218
Opened 2022-05-02 17:28 UTC by monicasalas86

## Description

Added "How did you hear about Underdog Devs?" to the mentee intake forms and created heard_about form values.
Pair programmed with Benedict Schurwanz.

#### Video Link

[Loom Video](https://www.loom.com/share/932ae73518824979ba6410556e55b78b)

#### Trello Link

https://trello.com/c/c3PAVHge/348-mentee-intake-additional-questions

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-05-02 17:50 UTC, mikayla-kosmala commented on src/components/pages/RoleSignup/Applications/Mentee.js
> +  const [formValues, handleChange, , setFormValues] = useForms(
is the ", ," supposed to be there?

2022-05-02 17:50 UTC, mikayla-kosmala requested changes
Add a loom video showing off the new feature!

2022-05-02 22:54 UTC, mikayla-kosmala approved these changes
Nice job on getting this done on your first day! Make sure you give @benedictSchurwanz credit since he helped pair program with you! Other than that good job!

2022-05-02 22:55 UTC, mikayla-kosmala commented
Also make sure you do a git pull origin main

2022-05-03 17:02 UTC, clairelist commented
Looks good! Great to have this functionality.

2022-05-03 17:03 UTC, clairelist approved these changes
And approved!

2022-05-03 23:15 UTC, kimnivore approved these changes

2022-05-03 23:15 UTC, kimnivore commented on src/components/pages/RoleSignup/Applications/Mentee.js
> +                  <Form.Item
Good job implementing the form with the various dropdown options.  Was there consideration to include an option for 'Other', if none of the previous options applied?

2022-05-04 05:24 UTC, merged