Feature/add ref questions
BloomTech-Labs/underdog-devs-fe-a pull request #220
Opened 2022-05-02 21:36 UTC by clairelist

## Description

Adds referral questions to mentor intake form.

#### Video Link

[Loom Video](https://www.loom.com/share/3a851deaaba942ba8fa1b1a2be67c4fd)

#### Trello Link

___Paste your trello card link here, deleting this example___

(Example below):

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JfipwNkb&#x2F;265-fix-refactor-sidebar-to-have-icons-representing-each-element-in-the-sidebar">Fix: Refactor sidebar to have icons representing each element in the sidebar</a></blockquote>

## Type of change

___Please delete options that are not relevant.___

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-05-02 22:27 UTC, clairelist commented
Important note: until someone (me, probably, since I have the ticket assigned on trello) builds backend functionality, this DOES break mentor intake for now -- will just have to add new fields.

2022-05-03 17:20 UTC, mikayla-kosmala requested changes
Do a git pull origin main to help fix the issue with the second test not passing

2022-05-03 20:46 UTC, mikayla-kosmala approved these changes
Looks good! Thanks for the quick turnaround

2022-05-03 23:13 UTC, amarrazza approved these changes
great job on adding additional form inputs, approved

2022-05-03 23:13 UTC, amarrazza commented on src/components/pages/RoleSignup/Applications/Mentor.js
> +                        message: 'Commitment is required.',
nice error messages

2022-05-04 05:28 UTC, merged