Refactor/intake forms tech stack
BloomTech-Labs/underdog-devs-fe-a pull request #240
Opened 2022-05-27 23:20 UTC by ryanghoward

## Description

Change form functionality to restrict users to only select one "tech_stack".  Update "tech_stack" data type to be an array.

#### Video Link

https://www.loom.com/share/2db99d6072ab4125800c1a14e0f3beb9

#### Trello Link

https://trello.com/c/s7Ecg99q/393-refactor-mentee-intake-form

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-05-28 10:04 UTC, leila-alhemali requested changes
Nice work! This is a clean, quick solution for the Mentee Form! 

This solution doesn't work for the Mentor Form because it only allows users to select one "tech_stack". 

We want Mentors to be able to select multiple values from  "tech_stack" to have them sent to the DB/BE in an array. The reasoning is so Mentors can help Mentees with multiple topics. However, Mentees are intended to only choose one "track" so "tech_stack" for the Mentees DB is a string. 

A potential design to fix this problem is to have a plus sign next to the tech_stack box so users can create more boxes. Another solution is having the checkboxes instead of a drop-down as it was before.

2022-05-31 20:45 UTC, FftyShadesofCode approved these changes
Looks great. I know the request from Leila was made. So everything should be in order.

2022-05-31 22:30 UTC, leila-alhemali approved these changes

2022-06-02 19:56 UTC, merged

2022-06-03 07:27 UTC, MingjunGeng commented
good , I see the 6ab70fea8c1f6200549061db4af4a563f4c61b16 have chage Mentor.js but the c961125e5c269305d5ad2edec6c8813889ee1180 change back . I don't know why