Created calendar file and added it to feature1
BloomTech-Labs/underdog-devs-fe-a pull request #25
Opened 2021-11-11 03:39 UTC by iwood55

## Description

Created calendar feature and new route for it in the navbar. Motivation to create it was for the mentor/mentee dashboards. Will add another commit for underdog devs color scheme.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2021-11-11 09:58 UTC, JorshuaG requested changes
Could you submit a Loom video going over the code? Unfamiliar with Ant Design and I think team would benefit from a walkthrough.

2021-11-11 16:45 UTC, kennymiesner approved these changes
Great job on implementing this important piece of the dashboard puzzle. Would love to see how this looks on the frontend.

2021-11-12 00:00 UTC, taylorkangillescas approved these changes
Great job implementing what you research on ant design into your calendar. Excited to implement this into our dashboards

2021-11-12 06:06 UTC, johanna-rodriguez commented
Nice! it is good you are using Ant Design library. This is an important piece of the application. Good job.

2021-11-12 16:05 UTC, JorshuaG approved these changes

2021-11-12 16:23 UTC, tfbielawski reviewed
Isaac, nice work on the calendar. It's better than the one I was working on! I saw some css code commented out, but I know you said in your walk-through that you plan on doing styling next. Just thought I'd mention that.

2021-11-12 20:01 UTC, paulstgermain requested changes
Looking good here, except for the way you're designating, exporting, and importing your component - the component should be capitalized! If you can make that change, I can merge this PR.

2021-11-12 20:01 UTC, paulstgermain commented on src/components/common/Calendar.js
> +const calendarFeature = () => {
Component capitalization!

2021-11-13 17:18 UTC, gamboaldo approved these changes
great job building out this calendar with antd

2021-11-13 21:42 UTC, iwood55 commented on src/index.js
> +import calendarFeature from './components/common/Calendar';
Changing capitalization now!

2021-11-16 16:10 UTC, paulstgermain approved these changes

2021-11-16 17:32 UTC, merged