BL-111-fe-as-an-administrator-i-can-approve-or-reject-an-application-from-a-mentee-or-mentor-so-that-i-can-get-approved-users-onboarded
BloomTech-Labs/underdog-devs-fe-a pull request #281
Opened 2022-08-09 19:40 UTC by MelodyLayne

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

No new dependencies

Fixes # (issue)

## Loom Video

Please paste a link here of a quick loom video walking through what you did in your PR .

## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have removed unnecessary comments/console logs from my code
- [ x ] I have made corresponding changes to the documentation if necessary (optional)
- [ x ] My changes generate no new warnings
- [ x ] I have checked my code and corrected any misspellings
- [ x ] No duplicate code left within changed files
- [ x ] Size of pull request kept to a minimum
- [ x ] Pull request description clearly describes changes made & motivations for said changes

2022-08-10 00:20 UTC, nathancai97 submitted a review, later dismissed
The updated code with the necessary changes are easy to understand and organized. For your PR, adding a Loom video and a link to the Jira board ticket would be beneficial!

2022-08-10 02:03 UTC, miguelaledesma approved these changes
Great work on this PR. Only thing i would probably do differently is remove console.logs and a Loom before creating the final push to create the PR. Other than that, good fix and great work updating the axios requests and fixing the buttons functionality.

2022-08-10 12:40 UTC, MelodyLayne commented
> The updated code with the necessary changes are easy to understand and organized. For your PR, adding a Loom video and a link to the Jira board ticket would be beneficial!

@nathancai97 The Loom will be up today and I completely forgot about adding the link to Jira. Great suggestion and I will add that.

2022-08-10 12:41 UTC, MelodyLayne commented
> Great work on this PR. Only thing i would probably do differently is remove console.logs and a Loom before creating the final push to create the PR. Other than that, good fix and great work updating the axios requests and fixing the buttons functionality.

@miguelaledesma thank you for catching that, we'll go clear those console logs and re-push it.

2022-08-10 16:25 UTC, jettyblue submitted a review, later dismissed
Nice updates here by fixing the buttons function and axios. Looks good, nice work!

2022-08-10 17:05 UTC, miguelaledesma approved these changes
Code looks clean now, no more unnecessary console logs YAY :)  Great job on this fix!

2022-08-10 18:03 UTC, nathancai97 approved these changes
Thank you for updating the PR so quickly! Everything looks ready to be deployed :)

2022-08-11 02:08 UTC, paulstgermain requested changes
This is a great fix - but I can't merge it up without a Loom video walking through the changes you made here! 😱 

Please record and post a link to a Loom video walking us through this ASAP and we'll get this merged up!

2022-08-11 12:04 UTC, MelodyLayne commented
> This is a great fix - but I can't merge it up without a Loom video walking through the changes you made here! 😱
> 
> Please record and post a link to a Loom video walking us through this ASAP and we'll get this merged up!

@paulstgermain  Loom video link, walkthrough done by the esteemed Christwide Oscar!

2022-08-11 16:36 UTC, Rlauckern approved these changes
Great changes and loom Video. Very organized and professional.

2022-08-15 16:22 UTC, Rlauckern submitted a review, later dismissed
Looking good. Nice changes from the comments and great organization!

2022-08-15 17:07 UTC, zdravoj submitted a review, later dismissed
Thanks for connecting this to the correct data pipeline! Nice work.

2022-08-16 15:11 UTC, miguelaledesma submitted a review, later dismissed
Thank you for removing the console logs, re-reviewing to approve the updated changes

2022-08-16 19:23 UTC, nathancai97 approved these changes
Great job implementing all these changes and updates!

2022-08-17 17:12 UTC, farhaannishtar reviewed
Great work hitting the endpoint needed to give the admin the ability to approve / reject the application. 👍

2022-08-17 17:14 UTC, farhaannishtar approved these changes

2022-08-17 20:13 UTC, jettyblue approved these changes
Looks great, nice work and addition of the Loom recording!

2022-08-17 22:29 UTC, techlando approved these changes
well written. good job!
also very helpful comments

2022-08-18 02:46 UTC, Johnjx commented on src/components/pages/PendingApplications/ApplicationModal.js
> +    console.log(currentApplication);
Is this clog still making it through?

2022-08-18 02:49 UTC, Johnjx reviewed
Well met addition of code comments to help explain the process. I would highly advise doing a quick walkthrough of the area of the website that concerns this PR, highlighting the elements in question that interact with these functions. For a new entrant into the codebase it is difficult to piece together the items that are being referenced and what the updates are.

2022-08-18 06:21 UTC, merged