Built out Mentee/Mentor signup with proper data sent to backend
BloomTech-Labs/underdog-devs-fe-a pull request #31
Opened 2021-11-13 09:32 UTC by Broveku

{{ENDPOINTS NEEDED FOR BOTH MENTOR AND MENTEE POST REQUESTS}}

## Description

Finished Mentor/Mentee intake forms with proper data being sent to the backend (missing endpoints)
Refactored how components are organized both with code, folders, and how rendered in Signup.js

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have removed unnecessary comments/console logs from my code
- [x ] I have made corresponding changes to the documentation if necessary (optional)
- [x ] My changes generate no new warnings
- [x ] I have checked my code and corrected any misspellings
- [x ] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x ] Pull request description clearly describes changes made & motivations for said changes

2021-11-13 22:03 UTC, JorshuaG approved these changes
Code looks clean and easy to read. Mentee and Mentor intake stores and sends desired information stakeholder previously handled using google forms and sends desired data to backend. Great job

2021-11-15 19:02 UTC, tfbielawski approved these changes
Really nice work. The only issue I see is a spelling error on line 121. "Stepend" should be "Stipend"

2021-11-16 18:39 UTC, paulstgermain requested changes
Unfortunately, I can't merge this PR until a Loom video explaining this PR and the changes made is submitted. Please create one and add the link to this PRs description as soon as possible!

2021-11-17 00:20 UTC, paulstgermain approved these changes

2021-11-17 00:20 UTC, merged