Bl 933 remove avatar from the application process
BloomTech-Labs/underdog-devs-fe-a pull request #310
Opened 2022-09-06 19:00 UTC by ezra-casas

## Description

Removed any association of the AVATAR icon.

Fixes # (issue)
Code Clean up
## Loom Video
(https://www.loom.com/share/1f752d4d972d4a3f9c86df636a084a52)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-09-07 15:30 UTC, Charles-Merrill-Johnson submitted a review, later dismissed
Good job here, pretty simple clean up.

2022-09-07 17:01 UTC, andrewgomez1992 submitted a review, later dismissed
Nice, easy clean up, I like it!

2022-09-07 17:37 UTC, Epeng1994 submitted a review, later dismissed
Code looks much cleaner now! Looking great

2022-09-07 22:18 UTC, stevenhastings approved these changes
Wonderful job, Ezra! I guess at this point we just cross our fingers and hope for Auth0 to oblige us, once and for all.  .   . While we're on the subject of Avatars; are we going to talk about the virtual world in the Unreal Engine sitting stage-right in that loom video. . . or, not? My interest is peaked.

2022-09-07 23:43 UTC, khaleel737 commented
Great job, looks cleaner now

2022-09-08 07:05 UTC, mcfrr3 requested changes
Everything looks good. I'm surprised you had to make changes in so many files 😬 😅 . 

I think line 21 in `src/components/pages/Navbar/Navbar.js` is also no longer necessary without the avatar in place

2022-09-08 17:59 UTC, jack-semder approved these changes
I think this is a must needed change, great work!

2022-09-08 19:20 UTC, theecolya reviewed
It does not look like you missed anything!

2022-09-08 21:19 UTC, farhaannishtar submitted a review, later dismissed
Looks great.

2022-09-09 00:14 UTC, Nicholas-R-Payne approved these changes
Good job removing this!

2022-09-09 16:20 UTC, mcfrr3 commented
> Everything looks good. I'm surprised you had to make changes in so many files 😬 😅 .
> 
> I think line 21 in `src/components/pages/Navbar/Navbar.js` is also no longer necessary without the avatar in place

Sorry, looking back I think it's line 20, where profilePic is being declared. Remove that line and I'll approve the change.

2022-09-12 18:47 UTC, Austin-T-Johnson commented
Nice job cleaning up the code everything looks good except you might want to remove line 8 in src/components/common/MemosTable/AddReply/showReply.js as well as line 20 in src/components/pages/Navbar/Navbar.js.
Other than that great job!

2022-09-12 18:57 UTC, MaxT6 approved these changes
Excellent work removing the Avatar from every profile. That should make the profiles clearer to their reviewers.

2022-09-12 18:57 UTC, MaxT6 commented on src/components/common/MemosTable/AddReply/showReply.js
> +          <span>{moment().subtract(2, 'days').fromNow()}</span>
nice job refactoring lines 30 and 32 to all be on one line.

2022-09-13 03:35 UTC, merged