BL-1066-be-fe-authentication-and-authorization-hook-ups
BloomTech-Labs/underdog-devs-fe-a pull request #334
Opened 2022-11-11 16:30 UTC by mina-mikhael

## Description

## Ticket BL-1066-be-fe-authentication-and-authorization-hook-ups

Intitially we had a BE middle-ware that was built to receive id_tokens, We needed to change it to receive an `accessToken` instead. 

The FE needed to get that token on demand and make sure that it's set on the `authorization header` on the request. That token was sometimes undefined.

Ticket objective is to wire FE API calls to BE private Endpoints through exchanging and verifying access_tokens by the auth. provider (auth0).

## Changes made to achieve the objective:

#### Back-End:

- Changed the audience in the .env file in order to verify access tokens instead of id tokens

#### Front-End:

- Added the audience in the .env file in order to add the add the correct header to the access token (jwt), to be verified later by the BE and the authProvider.
- Added the audience prop to the auth0Provider.
- Refactored the useAxiosWithAuth0 custom hook to create a new axios instance with the access token attached to the headers whenever we have authenticated user logged in.
- Fixed a bug in all private routes components that is supposed to consume the useAxiosWithAuth0 custom hook to add the access token to the request header when making api-call to private BE End-point.

### Video Link

[Loom Video](https://www.loom.com/share/9e12323c71734982b056eb55159f8f56)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-11-11 17:32 UTC, ryan-hamblin requested changes
The only change that I request will be in the documentation of the `interceptors` api on Axios.

2022-11-11 17:32 UTC, ryan-hamblin commented on src/components/common/MemosTable/AddReply/showReply.js
> +  const axiosWithAuth = useAxiosWithAuth0();
in the future, when you come across a linter warning go ahead and update in the file you're working on.

2022-11-11 17:32 UTC, ryan-hamblin commented on src/hooks/useAxiosWithAuth0.js
> +const axios_instance = axios.create({
Awesome! A little global to set the axios.create fn in scope! This is how it should've been done.

2022-11-11 17:32 UTC, ryan-hamblin commented on src/hooks/useAxiosWithAuth0.js
> +      axios_instance.interceptors.request.use(
can you cross link to the axios docs in a code comment somewhere here in the file? This is brilliant! https://axios-http.com/docs/interceptors

After talking through this logic surrounding `isAuthenticated` and learning a bit about axios.interceptors I feel confident this is the closest to the final solution we'd like too see!

2022-11-11 22:38 UTC, TylrPopcorn approved these changes
I think this should move the project toward a positive direction

2022-11-12 07:22 UTC, JamesFincher approved these changes
Clean. Will def help push things forward. Great work!

2022-11-14 18:56 UTC, merged