BL-1082 APPROVED GH ISSUE: home page Login button still show after the user is logged in
BloomTech-Labs/underdog-devs-fe-a pull request #339
Opened 2022-11-16 14:44 UTC by TylrPopcorn

**BL-1049 APPROVED GH ISSUE: home page Login button still show after the user is logged in**

## Issue
<img width="739" alt="Screen Shot 2022-11-16 at 9 13 19 AM" src="https://user-images.githubusercontent.com/104395322/202203366-34b15927-5b44-4495-b3b6-13703dfa65e0.png">

https://user-images.githubusercontent.com/104395322/202205475-6049bd70-53ab-4dd6-8d63-7cacc01de49d.mov

STEPS TO REPRODUCE:

1. Make sure you are logged OUT and head over to the landing page.
2. Click on the "Login" button and login.
3. After logging in, the homepage should have a button that says "Login" like in the video above.

-- -- --

### SOLUTION:

- Made changes to the LandingPage.js allowing for a fix to the issue currently at hand.
- After logging in, the button should no longer appear in the directory.
- Determined the problem was that there was no verification checking to see if the user is logged in and if anything should be hidden when logged in.

https://user-images.githubusercontent.com/104395322/202209143-15d8bc99-3993-4933-b4c9-601bebea464b.mov

## Type of change

- [🟩] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [🟩] My code follows the style guidelines of this project
- [🟩] I have performed a self-review of my own code
- [🟩] I have removed unnecessary comments/console logs from my code
- [🟩] I have made corresponding changes to the documentation if necessary (optional)
- [🟩] My changes generate no new warnings
- [🟩] I have checked my code and corrected any misspellings
- [🟩] No duplicate code left within changed files
- [🟩] Size of pull request kept to a minimum
- [🟩] Pull request description clearly describes changes made & motivations for said changes

2022-11-16 15:36 UTC, joanterm commented on src/components/pages/LandingPage/LandingPage.js
> +            ) : null}
Great use of a conditional statement! It makes more sense to fix this issue and remove the button once user is logged in.

2022-11-16 15:36 UTC, joanterm submitted a review, later dismissed

2022-11-16 17:02 UTC, gpwolfe reviewed
This does clearly remove the login button from the page after user is logged in. Should we also be removing the mentor/mentee sign-up fields from the page?
I don't know the front end, but the implication of the landing page is 1) Login OR 2) Sign up. If we're removing the one option after login, it seems to make sense to also remove the other, unless people can create accounts without applying to be a mentor or mentee.

2022-11-16 17:13 UTC, mina-mikhael submitted a review, later dismissed

2022-11-16 17:13 UTC, mina-mikhael commented on src/components/pages/LandingPage/LandingPage.js
> +  const { loginWithRedirect, isAuthenticated } = useAuth0();
relying on auth0 to check whether the user is authenticated to conditionally render the login component is smart

2022-11-16 17:16 UTC, JamesFincher submitted a review, later dismissed
Nice easy fix!

2022-11-16 18:44 UTC, TylrPopcorn commented
> This does clearly remove the login button from the page after user is logged in. Should we also be removing the mentor/mentee sign-up fields from the page? I don't know the front end, but the implication of the landing page is 1) Login OR 2) Sign up. If we're removing the one option after login, it seems to make sense to also remove the other, unless people can create accounts without applying to be a mentor or mentee.

This is a good point. I would need clarification on this part and if I should include the rest of the buttons or not.

2022-11-17 17:51 UTC, paulstgermain commented
> > This does clearly remove the login button from the page after user is logged in. Should we also be removing the mentor/mentee sign-up fields from the page? I don't know the front end, but the implication of the landing page is 1) Login OR 2) Sign up. If we're removing the one option after login, it seems to make sense to also remove the other, unless people can create accounts without applying to be a mentor or mentee.
> 
> This is a good point. I would need clarification on this part and if I should include the rest of the buttons or not.

@TylrPopcorn I would actually agree - once we've logged in, we have no reason to register. This would be a smooth update to the UI for existing users!

2022-11-17 17:52 UTC, paulstgermain requested changes

2022-11-17 17:52 UTC, paulstgermain commented on src/components/pages/LandingPage/LandingPage.js
>              <h3>Ready to Join Underdog Devs?</h3>
Let's go ahead and include the "Ready to Join" CTA and buttons to this conditional rendering. Once we're logged in, we don't need these anymore!

2022-11-17 18:30 UTC, TylrPopcorn commented
@paulstgermain Ok. I have just made those changes.

2022-11-17 18:35 UTC, paulstgermain approved these changes

2022-11-17 18:36 UTC, paulstgermain commented
> @paulstgermain Ok. I have just made those changes.

@TylrPopcorn Perfect, thanks - looking forward to merging this up once we get a few more reviews. Great work! 😄

2022-11-17 18:49 UTC, gpwolfe approved these changes
This looks good from what I can see, wrapping up all application/login in a single disappearing act.

2022-11-17 19:13 UTC, mina-mikhael approved these changes

2022-11-18 02:11 UTC, JamesFincher approved these changes

2022-11-18 16:38 UTC, merged