when super admin logs in it redirected to landing page. Fixed it and …
BloomTech-Labs/underdog-devs-fe-a pull request #355
Opened 2023-02-09 17:01 UTC by lailaarkadan

## Description
When Super Admin logs in, they are redirected back to the landing page instead of the applications page. 
Fixes # (issue)

## Loom Video
https://www.loom.com/share/0af891bc5c30419bacfd10dc043d6fbb

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2023-02-09 17:13 UTC, morganmallen approved these changes

2023-02-09 17:13 UTC, a-guillu reviewed
This looks like an effective way to clean the code by implementing the conditionals in one statement as opposed to having them separated in multiple lines. Way to get the admin login redirected to the landing page!

2023-02-09 17:16 UTC, branden-jones requested changes
simple fix that works.. should we delete the imports that arent being used... useState and useEffect. we may need these things later when we write more generic code... but for now it should be fine

2023-02-09 17:16 UTC, branden-jones commented on src/components/pages/Dashboard/Dashboard.js
> +  if (user.email.includes('001') || user.email.includes('002')) {
Good job catching that... I wrote this conditional so sorry for not seeing that initially... Eventually we need to write more generic router, but for now this works.

2023-02-10 16:16 UTC, JessWillCode commented
@paulstgermain I wanted to double check with you before I override the merge to make sure everyone gets points!

2023-02-13 16:10 UTC, merged