Feature/pending
BloomTech-Labs/underdog-devs-fe-a pull request #53
Opened 2021-12-13 23:34 UTC by rickmansfield

## Description

Updates HomeContainer to render PendingAproval.js which now contains code for a sidebar and a message regarding the user's status. Here the goal was to ensure a new user that was still "pending" before being approved/denied a mentor/mentee role could see their application status. 

Fixes #
Card 7: As a pending user, after I register, I need to see a pending application message along with other pertinent information on my status.

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

https://www.loom.com/share/54c7164d3fdb4a19b1360b69ea468daa

at the end of this video, I was cut off. I simply ended by explaining that we removed the unnecessary routing from src>index.js for pendingApprovals

2021-12-14 00:03 UTC, Retrofitt approved these changes
Loom video does a great job of explaining the code you implemented. 
The code itself looks good, easy to read, and clean. Excellent work.

2021-12-14 05:16 UTC, ayv8er approved these changes

2021-12-14 05:16 UTC, ayv8er commented on src/index.js
>          <Route path="/availability" component={Availability} />
Would we be placing these routes, including this new pending approval in a Secure Route?

2021-12-14 23:28 UTC, cyberkade requested changes
No hate against color customized bars, but I remember you saying you were gonna take this out before finishing the PR. Did you finish up and commit everything you wanted to?

2021-12-15 02:57 UTC, teresafranxman97 approved these changes
Very lucky to have been able to see this feature in action! Code is clean and readable, I also like the fact that pending users are still able to see the dark mode feature on their dashboard! Adds a great user experience to preview one of many great features the app has to show! Awesome job!

2021-12-15 14:40 UTC, RaphaelHebert commented
Neat code. Pull request helps to follow your work and review the code. Well done, great job.

2021-12-15 16:29 UTC, cyberkade approved these changes
Let's get this merged!

2021-12-15 17:02 UTC, merged