Feature/redux
BloomTech-Labs/underdog-devs-fe-a pull request #56
Opened 2021-12-15 18:48 UTC by ayv8er

## Description

Set up Redux to manage state of user profile. We'd eventually like to have Redux manage state of all profile information, calendar events and tickets. Installed dependencies, redux, react-redux, redux-thunk, redux-promise.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [X] My changes generate no new warnings
- [X] I have checked my code and corrected any misspellings
- [X] No duplicate code left within changed files
- [X] Size of pull request kept to a minimum
- [X] Pull request description clearly describes changes made & motivations for said changes

[](https://www.loom.com/share/2afa6dc0e943460897a23f9946ec705c)

2021-12-15 19:02 UTC, nhamilton1 requested changes
Fantastic work as usual! We should implement this small change before we merge this.

2021-12-15 19:05 UTC, nhamilton1 approved these changes

2021-12-16 15:40 UTC, RaphaelHebert commented
Nice work. Helpful and detailed video to explain the changes and their effects.

2021-12-16 16:43 UTC, Chris-Boyle-94 approved these changes
Great start to having redux in place for all of the profile components

2021-12-16 16:56 UTC, merged