fixed the login error message to accurately display when cerdentials …
BloomTech-Labs/underdog-devs-fe-a pull request #74
Opened 2022-01-21 15:34 UTC by Danielhk832

## Description

I changed the Okta error message for invalid credentials to more clearly display to the user what is preventing them from logging in. Previously, the error for invalid username or PW would read "Unable to sign in." This error message is ambiguous and doesn't convey to the user whether there is a technical issue with the sign-in service or whether they just misspelled their email or password. Now, the error message reads "Invalid Credentials" so users are more aware of the issue preventing them from signing-in.

Co-authored by: Emmanual (Manny) Gatica <egatica51@gmail.com>

Fixes # (issue)

Ambiguous sign-in error message.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-01-21 15:53 UTC, Shane-Gray394 approved these changes
Very simple, straightforward change. I can see why you wanted the message to more explicit, while at the same time not being a security concern.

2022-01-21 18:04 UTC, krueng approved these changes
Relatively a small PR which is easier to review. 
This message is now should clearly help the user during the logging-in process. 
Good catch!

2022-01-21 22:50 UTC, jimlemoine approved these changes
Super clean fix, the users will appreciate the proper context for what's happening when they have a sign-in credential error.

2022-01-21 22:57 UTC, paulstgermain requested changes
Nice catch here, Lance! That said, you forgot to include a walkthrough Loom for this PR - and I need to see one before I can merge this thing! Please include a short video talking about how you came across this fix, how it works, and why the change was made before I merge it up. 😀

2022-01-22 03:45 UTC, Danielhk832 commented
> Nice catch here, Daniel! That said, you forgot to include a walkthrough Loom for this PR - and I need to see one before I can merge this thing! Please include a short video talking about how you came across this fix, how it works, and why the change was made before I merge it up. 😀

Thanks, I have added the video

2022-01-24 16:43 UTC, kennedybryant approved these changes
So little code, such a huge change! I appreciate your attention to detail here in catching the ambiguous error message. It's these details that will give our users a great experience upon launch. I also appreciate that you showed the previous error message in your video. Great work!

2022-01-26 21:48 UTC, johnfigs approved these changes
This is a good catch. Glad to have this improved. Approving.

2022-02-01 22:49 UTC, waddal approved these changes
Nice catch, and definitely an improvement from the ambiguous error message that was in place previously.

2022-02-02 06:40 UTC, riqthedev approved these changes
Incredible way of thinking from the point of view of the user. Giving clear errors to users is huge.

2022-02-02 16:35 UTC, paulstgermain approved these changes

2022-02-02 16:35 UTC, merged