Feature/dropdown
BloomTech-Labs/underdog-devs-fe-a pull request #84
Opened 2022-02-03 23:43 UTC by riqthedev

## Description

Added dropdown menu for tech stack field

## Loom :

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-02-15 23:35 UTC, tinaxgao requested changes
It seems like there are too many updates in this PR, so maybe remove changes to the file that has conflicts.

2022-02-15 23:37 UTC, MrJacobSullivan requested changes
It looks like your local Prettier config is overriding the project Prettier config. Thus, when you run `npm run prettier` it conforms the entire project to your settings. This PR makes changes to 43 files. I think you should rethink the scope of this PR. You are making substantial changes to the landing page even though the PR is called `dropdown`.

2022-02-15 23:37 UTC, MrJacobSullivan commented on package.json
> +    "antd": "^4.18.4",
Why change the version of this package?

2022-02-15 23:37 UTC, MrJacobSullivan commented on package.json
> +    "rc-field-form": "^1.22.1",
Why the new package? Is it worth the technical debt?

2022-02-15 23:37 UTC, MrJacobSullivan commented on src/components/pages/FooterLanding/FooterLanding.js
> +// );
This commented code should be deleted.

2022-02-15 23:37 UTC, MrJacobSullivan commented on src/components/pages/LandingPage/LandingPage.css
> +.landInfo1 {
Why the combination of CSS and styled-components?

2022-02-18 00:23 UTC, cainpalmer requested changes
Could you split this PR into multiple ones? It would make it easier to review the code and check for feedback!

2022-02-18 20:23 UTC, paulstgermain commented
Merging this PR - the excess in files changed are actually coming from having this branch be brought up to speed with changes it didn't have from `main` as a side effect of the rebase flow.

2022-02-18 20:23 UTC, merged