Style/applications
BloomTech-Labs/underdog-devs-fe-a pull request #89
Opened 2022-02-11 15:45 UTC by riqthedev

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] No duplicate code left within changed files
- [ ] Size of pull request kept to a minimum
- [ ] Pull request description clearly describes changes made & motivations for said changes

2022-02-11 23:40 UTC, cainpalmer commented on src/styles/styles.css
> +
clean up spacing?

2022-02-11 23:46 UTC, cainpalmer requested changes
PR is good length and Loom video clear, however besides the spacing that can be cleaned up it seems there are some conflicting files.

2022-02-15 23:05 UTC, tinaxgao requested changes
Thanks for the update, the styling changes are clear. my team will continue working on the signup forms after your update. Just take a look at the current conflicts.

2022-02-18 20:33 UTC, tinaxgao approved these changes

2022-02-18 21:43 UTC, cainpalmer approved these changes
Nice changes! looks great!

2022-02-21 03:24 UTC, merged