Feature/redux dev
BloomTech-Labs/underdog-devs-fe-a pull request #93
Opened 2022-02-17 23:10 UTC by ryansnorek

# Loom recording
https://www.loom.com/share/d325ea625182483fbd6f7ea11bfa7541

## Description
These changes are the first step to converting the HomeContainer (HomePage) functionality into redux for easier state management. The original code in Home Page is still in tact and the redux function that would replace it's useEffect calls, is not connected. 

Redux functions added:
1. authenticateUser
2. setUserInfo
3. getUserProfile
4. fetchStart

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-02-17 23:49 UTC, cainpalmer approved these changes
PR is very clean and easy to read, code is mocked up and clean as well. I see there seems to be multiple items defined but not used. Other than that the code looks great.

2022-02-18 13:59 UTC, MrJacobSullivan requested changes
This is really good work! I especially like the fact that we will now be tracking when state is pending. I think there are a few changes we could make in this PR. It would be very helpful if we tracked errors in application state.

2022-02-18 13:59 UTC, MrJacobSullivan commented on src/state/actions/index.js
> +export const FETCH_START = 'FETCH_START';
This will be useful for handling loading state, nice work!

2022-02-18 13:59 UTC, MrJacobSullivan commented on src/state/actions/index.js
> +        console.log(err);
Could we handle this error in state? That way, if there's an error connecting to the backend, we could let the user know in a friendly way.

2022-02-18 13:59 UTC, MrJacobSullivan commented on src/state/reducers/userReducer.js
> +import * as a from '../actions/index';
Just a pet peeve of mine, but could we rename `a` to `ACTIONS` or something? Single-letter variables can get difficult to keep track of. Especially down the road when our redux store is significantly larger than it is now.

2022-02-18 13:59 UTC, MrJacobSullivan commented on src/state/reducers/userReducer.js
>    profile: '',
At this point, can we delete `photo` and `profile` from state? It seems all profile data should be handled in `userInfo` and we aren't currently storing photos of users.

2022-02-18 21:21 UTC, MrJacobSullivan approved these changes
Thank you for adding error handling to the application state! This is a great foundation from which we can build our redux store.

2022-02-21 03:28 UTC, paulstgermain commented on src/components/pages/Home/HomeContainer.js
> +  }, [dispatch, authService]);
_Love_ seeing this shortening and sweetening of our code here - keep it up!

2022-02-21 03:30 UTC, paulstgermain commented on src/components/pages/NavBarLanding/NavBarLanding.js
> +  console.log(props);
Let's make a note to remove this `console.log()` in the future! 😉

2022-02-21 03:32 UTC, paulstgermain commented on src/state/actions/index.js
> +// };
Let's make a decision on this commented-out code ASAP!

2022-02-21 03:35 UTC, paulstgermain commented
Additional note I'd like to make here - this is a textbook example of what we're looking from in our PR descriptions. Great work and detail here!

2022-02-21 03:44 UTC, merged