Feature/mentor application
BloomTech-Labs/underdog-devs-fe-a pull request #98
Opened 2022-02-20 22:11 UTC by danielaescutia07

## Description

https://www.loom.com/share/f2ba8df6e143420cba1c0654c304a283

This PR improves questions as well as options to choose from in lieu of text boxes on the Mentor Form.  This modification provides a preferable user experience by supplying the user with multiple options. This change will allow DS to utilize the data for mentor-mentee pairing suggestions.

## Contributors

@danielaescutia07 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [ ] I have made corresponding changes to the documentation if necessary (optional)
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-02-21 04:38 UTC, tinaxgao requested changes

2022-02-21 04:38 UTC, tinaxgao commented on src/components/pages/RoleSignup/Applications/Mentee.js
>  import React, { useState } from 'react';
Please don't include the Mentee file in this PR

2022-02-21 04:38 UTC, tinaxgao commented on src/components/pages/RoleSignup/Applications/Mentor.js
> +  function handleChangeStates(value) {
see my updated mentee file for examples for this & all the onChange functions

2022-02-21 15:24 UTC, tinaxgao requested changes

2022-02-21 15:24 UTC, tinaxgao commented on src/components/pages/RoleSignup/Applications/Mentor.js
>                      <Input placeholder="Your answer" />
You need to add an onChange here to record the value

2022-02-21 16:10 UTC, tinaxgao approved these changes
great changes to update mentor form to accept more relevant data for DS. Looks consistent with Mentee form.

2022-02-21 17:26 UTC, tristanharrower approved these changes
The changes satisfy the DS requirements and are written effectively.  Good Job!

2022-02-22 07:25 UTC, merged

2022-03-04 14:44 UTC, AnthonyMillerGit reviewed
the text boxes being changed was great. just needs to be a bit more responsive on mobile